export const mockRents = [
    {
        id: 1,
        client: 'Иванов Иван Иванович',
        bike: 'BIKE-001',
        battery_capacity: 500,
        battery_count: 2,
        tariff: { program: 'Обычная' },
        tariff_type: 'month',
        tariff_price: 2500,
        start_date: '2025-01-01',
        end_date: '2025-01-31',
        cost: 2500,
        paid: 'paid',
        is_completed: true,
        note: 'Аренда на месяц. Полная предоплата.',
    },
    {
        id: 2,
        client: 'Петрова Анна Сергеевна',
        bike: 'BIKE-002',
        battery_capacity: 360,
        battery_count: 1,
        tariff: { program: 'Самокат' },
        tariff_type: '1 week',
        tariff_price: 600,
        start_date: '2025-02-10',
        end_date: '2025-02-17',
        cost: 600,
        paid: 'paid',
        is_completed: true,
        note: 'Неделя. Оплата при получении.',
    },
    {
        id: 3,
        client: 'Сидоров Дмитрий Алексеевич',
        bike: 'BIKE-003',
        battery_capacity: 500,
        battery_count: 2,
        tariff: { program: 'Купер' },
        tariff_type: '1 week',
        tariff_price: 1200,
        start_date: '2025-03-01',
        end_date: null,
        cost: 1200,
        paid: 'unpaid',
        is_completed: false,
        note: 'Первая неделя. Оплата после возврата.',
    },
    {
        id: 4,
        client: 'Козлова Мария Петровна',
        bike: 'BIKE-004',
        battery_capacity: null,
        battery_count: 0,
        tariff: { program: 'Обычная' },
        tariff_type: '1 week',
        tariff_price: 800,
        start_date: '2025-03-05',
        end_date: '2025-03-12',
        cost: 800,
        paid: 'paid',
        is_completed: true,
        note: 'Без АКБ — только велосипед.',
    },
    {
        id: 5,
        client: 'Николаев Сергей Владимирович',
        bike: 'BIKE-005',
        battery_capacity: 720,
        battery_count: 2,
        tariff: { program: 'Купер' },
        tariff_type: 'next weeks',
        tariff_price: 1100,
        start_date: '2025-03-15',
        end_date: null,
        cost: 2200,
        paid: 'unpaid',
        is_completed: false,
        note: '2 недели. Рассрочка.',
    },
    {
        id: 6,
        client: 'Федорова Елена Михайловна',
        bike: 'BIKE-006',
        battery_capacity: 360,
        battery_count: 1,
        tariff: { program: 'Самокат' },
        tariff_type: 'month',
        tariff_price: 1800,
        start_date: '2025-04-01',
        end_date: '2025-04-30',
        cost: 1800,
        paid: 'paid',
        is_completed: true,
        note: 'Месяц. Предоплата.',
    },
    {
        id: 7,
        client: 'Морозов Павел Андреевич',
        bike: 'BIKE-007',
        battery_capacity: 500,
        battery_count: 2,
        tariff: { program: 'Обычная' },
        tariff_type: 'next weeks',
        tariff_price: 700,
        start_date: '2025-04-05',
        end_date: null,
        cost: 700,
        paid: 'unpaid',
        is_completed: false,
        note: 'Вторая неделя. Оплата при возврате.',
    },
    {
        id: 8,
        client: 'Волкова Ольга Николаевна',
        bike: 'BIKE-008',
        battery_capacity: 500,
        battery_count: 2,
        tariff: { program: 'Обычная' },
        tariff_type: 'month',
        tariff_price: 2500,
        start_date: '2025-04-10',
        end_date: '2025-05-10',
        cost: 2500,
        paid: 'paid',
        is_completed: true,
        note: 'Месяц. Акция.',
    },
    {
        id: 9,
        client: 'Лебедев Артем Юрьевич',
        bike: 'BIKE-009',
        battery_capacity: 360,
        battery_count: 1,
        tariff: { program: 'Самокат' },
        tariff_type: 'next weeks',
        tariff_price: 550,
        start_date: '2025-04-15',
        end_date: null,
        cost: 1100,
        paid: 'unpaid',
        is_completed: false,
        note: '2 недели. Рассрочка.',
    },
    {
        id: 10,
        client: 'Смирнова Дарья Александровна',
        bike: 'BIKE-010',
        battery_capacity: 720,
        battery_count: 2,
        tariff: { program: 'Купер' },
        tariff_type: 'month',
        tariff_price: 4000,
        start_date: '2025-05-01',
        end_date: null,
        cost: 4000,
        paid: 'paid',
        is_completed: false,
        note: 'Месяц. Полная предоплата.',
    },
    {
        id: 11,
        client: 'Кузнецов Роман Викторович',
        bike: 'BIKE-011',
        battery_capacity: null,
        battery_count: 0,
        tariff: { program: 'Обычная' },
        tariff_type: '1 week',
        tariff_price: 800,
        start_date: '2025-05-05',
        end_date: '2025-05-12',
        cost: 800,
        paid: 'paid',
        is_completed: true,
        note: 'Только велосипед. Неделя.',
    },
    {
        id: 12,
        client: 'Попова Екатерина Дмитриевна',
        bike: 'BIKE-012',
        battery_capacity: 500,
        battery_count: 2,
        tariff: { program: 'Обычная' },
        tariff_type: 'next weeks',
        tariff_price: 700,
        start_date: '2025-05-10',
        end_date: null,
        cost: 1400,
        paid: 'unpaid',
        is_completed: false,
        note: '2 недели. Оплата при возврате.',
    },
    {
        id: 13,
        client: 'Васильев Илья Максимович',
        bike: 'BIKE-013',
        battery_capacity: 360,
        battery_count: 1,
        tariff: { program: 'Самокат' },
        tariff_type: 'month',
        tariff_price: 1800,
        start_date: '2025-05-15',
        end_date: '2025-06-14',
        cost: 1800,
        paid: 'paid',
        is_completed: true,
        note: 'Месяц. Акция.',
    },
    {
        id: 14,
        client: 'Павлов Алексей Константинович',
        bike: 'BIKE-014',
        battery_capacity: 720,
        battery_count: 2,
        tariff: { program: 'Купер' },
        tariff_type: '1 week',
        tariff_price: 1200,
        start_date: '2025-06-01',
        end_date: null,
        cost: 1200,
        paid: 'unpaid',
        is_completed: false,
        note: 'Первая неделя. Рассрочка.',
    },
    {
        id: 15,
        client: 'Соколова Вероника Сергеевна',
        bike: 'BIKE-015',
        battery_capacity: 500,
        battery_count: 2,
        tariff: { program: 'Обычная' },
        tariff_type: 'month',
        tariff_price: 2500,
        start_date: '2025-06-05',
        end_date: '2025-07-05',
        cost: 2500,
        paid: 'paid',
        is_completed: true,
        note: 'Месяц. Полная предоплата.',
    },
];
